# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Journey' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Journey
  pod 'React', :path => '/Users/maizhikun/Learning/apache_sites/Journey_Front/node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
      # 添加其他你想在工程中使用的依赖。
    ]


  target 'JourneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JourneyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
